---
- template:
    src: "{{ config }}"
    dest: "/tmp/bigip-{{ machine_fingerprint }}.conf"
  register: output 
  when: config is defined
  notify: merge bigip.conf

- include_tasks: setup_socats.yaml
  delegate_to: "{{ item.key }}"
  become: true
  become_method: sudo
  become_user: "{{ hostvars[item.key].become_user }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"
  when: item.key != 'localhost'

- template:
    src: "{{ apache_config }}"
    dest: "/tmp/apache-{{ item.key }}-{{ machine_fingerprint }}.conf"
    mode: 0666
  register: output
  when: apache_config is defined
  run_once: true
  delegate_to: "{{ item.key }}"
  vars:
    members: "{{ item.value }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"
  notify: make docker apache
