---
#- name: Clear bigip.conf
#  file:
#    state: "{{ item }}"
#    path: /config/bigip.conf
#  notify:
#    - load tmsh config    
#  with_items:
#    - absent
#    - touch 
#- debug: var=resources

#- debug: var=_

- shell:
    test -e {{ item.local_dir }} && fusermount -u {{ item.local_dir }} &&
    rmdir {{ item.local_dir }} || true

  delegate_to: localhost
  run_once: true
  with_items: "{{ resources.members }}"
  when: item.docker != 'localhost'

- shell:
    test -e {{ item.value.remote_dir }} && rmdir {{ item.value.remote_dir }} || true

  run_once: true
  delegate_to: "{{ item.key }}"
  with_dict_list: "{{ dict(resources.members | groupby('docker')) }}"

- set_fact:
    _: '{{ f5test_respools.get(item) and f5test_respools[item].free_all() }}'

  delegate_to: localhost
  run_once: true
  with_items: '{{ resources }}'
