---
- name: remove docker apache container
  docker_container:
    name: "apache-{{ machine_fingerprint }}"
    state: absent
  delegate_to: "{{ item.key }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"

- file:
    path: "{{ tmp_apache_conf }}"
    state: absent
  delegate_to: "{{ item.key }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"

- shell:
    test -e {{ item.local_dir }} && fusermount -u {{ item.local_dir }} &&
    rmdir {{ item.local_dir }}
  delegate_to: localhost
  run_once: true
  ignore_errors: yes
  with_items: "{{ resources.members }}"
  when: item.docker != 'localhost'

- setup:
    fact_path: ~/facts.d
  delegate_to: "{{ item.key }}"
  register: output
  become: "{{ ansible_user == 'root' }}"
  become_method: sudo
  become_user: "{{ hostvars[item.key].become_user }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"
  when: item.key != 'localhost'
  notify: kill socats

- shell:
    test -e {{ item.value.remote_dir }} && rm -rf {{ item.value.remote_dir }}
  run_once: true
  delegate_to: "{{ item.key }}"
  become: "{{ ansible_user == 'root' }}"
  become_method: sudo
  become_user: nobody
  ignore_errors: yes
  with_dict_list: "{{ dict(resources.members | groupby('docker')) }}"

- set_fact:
    _: '{{ f5test_respools.get(item) and f5test_respools[item].free_all() }}'

  delegate_to: localhost
  run_once: true
  with_items: '{{ resources }}'

- f5_unmerge:
    address: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    filename: "{{ tmp_bigip_conf }}"

- file:
    path: "{{ tmp_bigip_conf }}"
    state: absent
