---
- file:
    path: "{{ tmp_apache_conf }}"
    state: absent
  delegate_to: "{{ item.key }}"
  with_dict: "{{ dict(resources.members | groupby('docker')) }}"

- set_fact:
    _: '{{ f5test_respools.get(item) and f5test_respools[item].free_all() }}'

  delegate_to: localhost
  run_once: true
  with_items: '{{ resources }}'

# Caveat: In order to unmerge objects they must be listed in order of dependencies in the template.
# E.g.: Nodes, pools, virtuals
- f5_unmerge:
    address: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    filename: "{{ tmp_bigip_conf }}"

- file:
    path: "{{ tmp_bigip_conf }}"
    state: absent
